apiVersion: v1
kind: Namespace
metadata:
  name: ingress-controller
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
spec:
  destination:
    namespace: ingress-controller
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.1.3
    chart: ingress-nginx
    helm:
      parameters:
      - name: controller.replicaCount      
        value: '2'
      - name: controller.image.digest     
        value: ''
      - name: controller.service.annotations.service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path     
        value: '/healthz'
      - name: controller.admissionWebhooks.patch.image.digest     
        value: ''
      - name: defaultBackend.image.digest     
        value: ''
  sources: []
  project: default
